import {describe,it,expect} from 'vitest';
import {listingSteps,PRICE_REASON} from './listingSteps';
import {createStandardSelection} from '@/api/listingLicenses';
import type {SellerWorkspaceConnection} from '@/api/sellerWorkspace';
import type {ListingReview} from '@/api/sellerListingReview';
import type {PublicationReceipt} from '@/api/sellerListingPublication';
const source={version:2,connection_current:true,content:{connection_id:'c',connection_version:1,version_mode:'current' as const,objects:[{key:'sales.csv',etag:'e',size:10,version_id:null}]}};
const draft={version:3,updated_at:'2026-10-01T00:00:00Z',content:{brief:'Sales',title:'Sales',description:'Weekly sales',description_source_version:2,category:'financial-data',tags:'sales',price:'25',license:'Legacy',license_selection:{...createStandardSelection(),seller_acceptance:{signer_name:'Max Seller',signer_title:'Owner',authority_confirmed:true}}}};
const review={draft_version:3,source_version:2,missing_fields:[],approval:{id:'a'}} as unknown as ListingReview;
const base={source,draft,categories:[{slug:'financial-data',name:'Financial Data'}],connections:[{id:'c',version:1,status:'verified'} as SellerWorkspaceConnection],licensesEnabled:true,review:null,publication:null};
const step4=(content:Partial<typeof draft.content>)=>listingSteps({...base,draft:{...draft,content:{...draft.content,...content}}})[3];
describe('guided listing saved progress',()=>{
 it('names exactly one next step at every saved boundary',()=>{
  const boundaries=[{...base,source:null,draft:null,connections:[]},{...base,source:null,draft:null},{...base,draft:null},base,{...base,review},{...base,review,publication:{approval_id:'a'} as PublicationReceipt}];
  expect(boundaries.map(b=>listingSteps(b).filter(s=>s.next).length)).toEqual([1,1,1,1,1,0]);
  expect(boundaries.map(b=>listingSteps(b).find(s=>s.next)?.view)).toEqual(['storage','data','license','review','publish',undefined]);
  boundaries.forEach(b=>listingSteps(b).forEach(s=>{if(s.state!=='done')expect(s.reason.trim()).not.toBe('');}));
 });
 it('distinguishes work available to do from blocked dependencies',()=>{const steps=listingSteps({...base,connections:[],source:null,draft:null});expect(steps[2].state).toBe('to do');expect(steps[1].state).toBe('blocked');});
 it('skips licence choice when off',()=>{expect(listingSteps({...base,licensesEnabled:false,draft:null})[2].state).toBe('done');});
 it.each(['0','25','25.00','999999.99','00025.01'])('accepts backend admissible price %s',price=>{expect(step4({price}).state).toBe('done');});
 it.each(['','24.99','-1','1000000','25.001','1e2','NaN'])('refuses backend invalid price %s',price=>{expect(step4({price}).reason).toBe(PRICE_REASON);});
 it('requires a title and description',()=>{expect(step4({title:' '}).reason).toContain('Add a title');expect(step4({description:''}).reason).toContain('Add a description');});
 it('requires a category slug and at least one comma-separated tag',()=>{expect(step4({category:'Financial Data'}).reason).toContain('Choose a category from the list');expect(step4({tags:' , , '}).reason).toContain('Add at least one tag');});
 it('requires the exact saved source stamp after change or manual editing',()=>{expect(step4({description_source_version:1}).state).not.toBe('done');expect(step4({description_source_version:null as never}).state).not.toBe('done');});
 it('uses the current server refusal even when local checks pass',()=>{const steps=listingSteps({...base,review:{...review,missing_fields:['tags']}});expect(steps[3].state).toBe('current');expect(steps[3].reason).toContain('Add at least one tag');expect(steps[4].state).toBe('blocked');});
 it('shows an unexpected server reason and withdraws description completion',()=>{expect(listingSteps({...base,reviewReason:'Review refused: source_connection_changed.'})[3].reason).toBe('Review refused: source_connection_changed.');});
 it('ignores approval for another draft or source',()=>{expect(listingSteps({...base,review:{...review,draft_version:2}})[4].state).not.toBe('done');expect(listingSteps({...base,review:{...review,source_version:1}})[4].state).not.toBe('done');});
 it('withdraws progress while unsaved file, licence or listing edits remain',()=>{expect(listingSteps({...base,pending:true,review})[1].state).not.toBe('done');expect(listingSteps({...base,licenceDirty:true,review})[2].state).not.toBe('done');expect(listingSteps({...base,reviewReason:'Save your changes.',review})[4].state).not.toBe('done');});
 it('rejects a replaced connection even before the source is reloaded',()=>{expect(listingSteps({...base,connections:[{id:'c',version:2,status:'verified'} as SellerWorkspaceConnection]})[1].state).not.toBe('done');});
});
