import { expect, it } from 'vitest';
import { sessionCsrf } from './session-csrf';

// Generated by executing session_csrf from backend c26589a5's
// app/api/v1/endpoints/pending_actions.py with Python hashlib.
it.each([
  ['web-session', 'b70ecc869f6b960f4974d6393c8d77c144efb35447d2a0a8b801c37f6644ec37'],
  ['signed-session-credential', '3cf0a84f5ca58f2f3724c254c3e593be5694d0a6f2c03cb8d240a9a39434591b'],
  ['fake-session-é🔐', '93e34feec8d8816afb8b4b47fb2ce233153d62766348aefe76c0d1fcbb6c6d49'],
])('matches the backend session CSRF vector for %s', (token, digest) => {
  expect(sessionCsrf(token)).toBe(digest);
});
